name = "glexec"
version = "1.1.0"
licences = ["Apache-2.0"]
description = "A Gleam wrapper for erlexec"

repository = { type = "github", user = "manveru", repo = "gleam_erlexec" }
links = []

[dependencies]
erlexec = ">= 2.2.2 and < 3.0.0"
gleam_stdlib = "~> 0.36"
gleam_erlang = ">= 1.3.0 and < 2.0.0"


[dev-dependencies]
erlfmt = "~> 1.3"
gleeunit = "~> 1.0"
taskle = ">= 2.0.0 and < 3.0.0"
